[package]
name = "gqlmapi_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
cxx = "1.0.54"

[build-dependencies]
cmake = "0.1.45"
cxx-build = "1.0.54"

[dev-dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"