[package]
name = "gqlmapi-rs"
version = "0.2.0"
edition = "2018"
description = "Rust bindings for https://github.com/microsoft/gqlmapi"
repository = "https://github.com/wravery/gqlmapi-rs"
license = "MIT"
keywords = ["MAPI", "GraphQL", "gqlmapi"]
categories = ["os::windows-apis"]

[dependencies]
cxx = "1.0.54"

[build-dependencies]
cmake = "0.1.45"
cxx-build = "1.0.54"

[dev-dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"