[package]
name = "gqlmapi-rs"
version = "0.5.0"
edition = "2018"
description = "Rust bindings for https://github.com/microsoft/gqlmapi"
repository = "https://github.com/wravery/gqlmapi-rs"
license = "MIT"
keywords = ["MAPI", "GraphQL", "gqlmapi"]
categories = ["os::windows-apis"]

[features]
"crt-static" = ["cxx/crt-static"]
default = ["crt-static"]

[dependencies]
cxx = { git = "https://github.com/wravery/cxx" }
windows = "0.19.0"

[build-dependencies]
cmake = "0.1.45"
cxx-build = "1.0.54"
windows = "0.19.0"

[dev-dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"